
@Observed
export class Book {
  public bookName: string = "雪中悍刀行"
  public bookAuthor: string = "烽火戏诸侯"
  public bookDetail: string = `  这个江湖，有武夫自称天下第二一甲子。有剑仙一剑破甲两千六。有胆小的骑牛道士肩扛两道。但一样是这个江湖，可能是江湖儿郎江湖死，才初出茅庐，便淹死在江湖中。可能对一个未入江湖的稚童来说，抱住了一柄刀，便是抱住了整座江湖。而主角，一刀将江湖捅了个透！临了，喊一声：小二，上酒~
  小说关键词：雪中悍刀行无弹窗,雪中悍刀行txt全集下载,雪中悍刀行最新章节阅读
`
  public bookUpdateTime: Date = new Date("2016-07-03T23:47:03+08:00")
  public bookStatus: string = "已完结"
  public bookImage: string =  "https://www.biqugecn.com/files/article/image/0/807/807s.jpg"
  public bookRenqi: string = "8904"
  public bookTags: string = "玄幻"
  public bookLatestChapter: string = "贺新凉"

  public bookAllChapterNum: number = 953
  public bookPage: string = "https://www.biqugecn.com/book/807/"
  public bookReadChapter: number = 1
  public bookIsInShelf: boolean = false
  constructor() {
  }
}
